spring:
  application:
    name: hhplus-concert-jvm
  datasource:
    url: jdbc:h2:file:~/concert-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.connection.isolation: 2  # READ_COMMITTED
    show-sql: false
    open-in-view: false
