spring:
  application:
    name: hhplus-concert-jvm
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert
    username: hhplus
    password: hhplus1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
