spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert_test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
redisson:
  address: redis://${redis.host}:${redis.port}/1
