spring:
  application:
    name: hhplus-concert-jvm
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert
    username: hhplus
    password: hhplus1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hhplus-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
redis:
  host: 127.0.0.1
  port: 6379
  url: redis://${redis.host}:${redis.port}/0
  password: ""
  timeout: 3000
